// HTML templates for the docs generator. Hand-written SHELL semantics live in
// docs/assets/site.css + site.js; everything data-driven here comes from the
// contracts and the token artefacts, never hand-added (blueprint §2.3).
import type { TokenEntry, TokenModel } from "./docs-tokens.ts";

export interface ComponentDoc {
  slug: string; // folder name, kebab-case
  meta: {
    name: string;
    description: string;
    variants: { variant: string }[];
    states?: { state: string; note: string }[];
    notes?: string;
    examples: { label: string; props: Record<string, unknown>; children?: string }[];
    guidelines?: {
      golden: { rule: string; detail: string }[];
      do: string[];
      dont: string[];
    };
  };
  contract: {
    status: string;
    rfc?: string;
    designNode?: string;
    props?: Record<string, { type: string; default?: string; optional?: boolean; note?: string }>;
    a11y: {
      status: string;
      semanticStructure?: string;
      keyboard?: string;
      decisions?: string;
      notes?: string;
    };
  };
  renderedExamples: string[]; // same order as meta.examples
}

export const esc = (s: unknown): string =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const GENERATED =
  "<!-- GENERATED by `pnpm docs:build` (scripts/generate-docs.ts). Do not edit; edit the component contracts and regenerate. -->";

// JSX source of a contract example, shown under its demo stage (derived from
// the example, never hand-written).
function jsxSource(name: string, e: ComponentDoc["meta"]["examples"][number]): string {
  const attrs = Object.entries(e.props)
    .map(([k, v]) => (typeof v === "string" ? ` ${k}="${v}"` : ` ${k}={${JSON.stringify(v)}}`))
    .join("");
  return e.children !== undefined
    ? `<${name}${attrs}>${e.children}</${name}>`
    : `<${name}${attrs} />`;
}

// Decorate a rendered example's root element with a docs-only class (the
// forced-state mirrors in the generated lib.css target these classes).
function withForcedState(html: string, state: string): string {
  if (state === "default") return html;
  return html.replace(/class="/, `class="ll-docs-force-${state} `);
}

// One place defines a component page's section anchors; the sidebar submenu
// and the page headings both read it, so they cannot drift apart.
function sections(c: ComponentDoc): { label: string; anchor: string }[] {
  return [
    { label: "Examples", anchor: "examples" },
    ...(c.meta.guidelines ? [{ label: "Guidelines", anchor: "guidelines" }] : []),
    { label: "Accents", anchor: "accents" },
    ...(c.meta.states ?? []).map((s) => ({ label: s.state, anchor: `state-${s.state}` })),
    ...(c.contract.props ? [{ label: "Props", anchor: "props" }] : []),
    { label: "Accessibility", anchor: "accessibility" },
  ];
}

// The tokens page's section anchors — one definition feeds the sidebar submenu
// and the page headings, so they cannot drift apart. Collection sections come
// from the model (tokens.json order); "Theme axes" is a template section.
export function tokensSections(model: TokenModel): { label: string; anchor: string }[] {
  return [
    ...model.collections.map((c) => ({
      label: c.collection,
      anchor: c.collection.toLowerCase(),
    })),
    { label: "Theme axes", anchor: "axes" },
  ];
}

function sidebar(
  components: ComponentDoc[],
  tokenSections: { label: string; anchor: string }[],
  relRoot: string,
  current?: string,
): string {
  const tokensHref = `${relRoot}/tokens.html`;
  const tokensCurrent = current === "tokens";
  const tokensSub = tokenSections
    .map((s) => `        <li><a href="${tokensHref}#${s.anchor}">${esc(s.label)}</a></li>`)
    .join("\n");
  const items = components
    .map((c) => {
      const href = `${relRoot}/components/${esc(c.slug)}.html`;
      const isCurrent = c.slug === current;
      const sub = sections(c)
        .map((s) => `        <li><a href="${href}#${s.anchor}">${esc(s.label)}</a></li>`)
        .join("\n");
      return `    <li>
      <details${isCurrent ? " open" : ""}>
        <summary><a href="${href}"${isCurrent ? ' aria-current="page"' : ""}>${esc(c.meta.name)}</a></summary>
        <ul class="sub">
${sub}
        </ul>
      </details>
    </li>`;
    })
    .join("\n");
  return `<nav class="sidebar" aria-label="Documentation">
  <a class="registry-link" href="${relRoot}/index.html"${current === "registry" ? ' aria-current="page"' : ""}>Registry</a>
  <p class="sidebar-label">Foundations</p>
  <ul class="nav-list">
    <li>
      <details${tokensCurrent ? " open" : ""}>
        <summary><a href="${tokensHref}"${tokensCurrent ? ' aria-current="page"' : ""}>Design tokens</a></summary>
        <ul class="sub">
${tokensSub}
        </ul>
      </details>
    </li>
  </ul>
  <p class="sidebar-label">Components</p>
  <ul class="nav-list">
${items}
  </ul>
</nav>`;
}

export function layout(opts: {
  title: string;
  relRoot: string; // "." for root pages, ".." for component pages
  accents: string[];
  components: ComponentDoc[];
  tokenSections: { label: string; anchor: string }[];
  current?: string; // "registry" | "tokens" | a component slug
  content: string;
}): string {
  const { title, relRoot, accents, components, tokenSections, current, content } = opts;
  return `<!doctype html>
${GENERATED}
<html lang="en" data-accent="ambre">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<link rel="stylesheet" href="${relRoot}/assets/lib.css">
<link rel="stylesheet" href="${relRoot}/assets/site.css">
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header">
  <a class="site-title" href="${relRoot}/index.html">LearningLeagues Lib</a>
  <div class="switchers">
    <fieldset class="switcher" aria-label="Accent">
      <legend>Accent</legend>
${accents
  .map(
    (a) =>
      `      <button type="button" data-set-accent="${esc(a)}" aria-pressed="${a === "ambre"}">${esc(a)}</button>`,
  )
  .join("\n")}
    </fieldset>
  </div>
</header>
<div class="shell">
${sidebar(components, tokenSections, relRoot, current)}
<main id="main">
${content}
</main>
</div>
<footer class="site-footer">
  <p>Generated from the component contracts by <code>pnpm docs:build</code>. Content lives in the contracts, never here.</p>
</footer>
<script src="${relRoot}/assets/site.js"></script>
</body>
</html>
`;
}

export function indexPage(
  components: ComponentDoc[],
  accents: string[],
  tokenSections: { label: string; anchor: string }[],
): string {
  const rows = components
    .map(
      (c) => `      <tr>
        <th scope="row"><a href="./components/${esc(c.slug)}.html">${esc(c.meta.name)}</a></th>
        <td><span class="badge badge--${esc(c.contract.status)}">${esc(c.contract.status)}</span></td>
        <td>${c.meta.variants.map((v) => esc(v.variant)).join(", ") || "—"}</td>
        <td><span class="badge badge--${esc(c.contract.a11y.status)}">${esc(c.contract.a11y.status)}</span></td>
        <td>${esc(c.meta.description)}</td>
      </tr>`,
    )
    .join("\n");
  return layout({
    title: "Component registry — LearningLeagues Lib",
    relRoot: ".",
    accents,
    components,
    tokenSections,
    current: "registry",
    content: `<h1>Component registry</h1>
<p>Every row is generated from the component's own contract (<code>meta.ts</code> + <code>contract.json</code>).</p>
<table>
  <thead>
    <tr><th scope="col">Component</th><th scope="col">Status</th><th scope="col">Variants</th><th scope="col">A11y</th><th scope="col">Description</th></tr>
  </thead>
  <tbody>
${rows}
  </tbody>
</table>`,
  });
}

export function componentPage(
  c: ComponentDoc,
  accents: string[],
  components: ComponentDoc[],
  tokenSections: { label: string; anchor: string }[],
): string {
  // Top stage: every example live in one row (interactive — all CSS states
  // work here), with the JSX each one came from underneath.
  const exampleStage = `<div class="stage">
${c.renderedExamples.map((html) => `  ${html}`).join("\n")}
</div>
<pre class="code"><code>${c.meta.examples.map((e) => esc(jsxSource(c.meta.name, e))).join("\n")}</code></pre>`;
  // Guidelines: golden rules as a numbered card, do/dont as ✓/✗ columns —
  // contract content (meta.guidelines), rendered here, never hand-listed.
  const g = c.meta.guidelines;
  const guidelinesHtml = g
    ? `<h2 id="guidelines">Guidelines</h2>
<div class="golden">
  <p class="golden-title">Golden rules</p>
  <ol>
${g.golden.map((r) => `    <li><strong>${esc(r.rule)}.</strong> ${esc(r.detail)}</li>`).join("\n")}
  </ol>
</div>
<div class="dos-donts">
  <div class="dos">
    <p class="dos-title">Do</p>
    <ul>
${g.do.map((d) => `      <li>${esc(d)}</li>`).join("\n")}
    </ul>
  </div>
  <div class="donts">
    <p class="donts-title">Don't</p>
    <ul>
${g.dont.map((d) => `      <li>${esc(d)}</li>`).join("\n")}
    </ul>
  </div>
</div>
`
    : "";
  const firstExample = c.renderedExamples[0] ?? "";
  const accentTiles = accents
    .map(
      (a) => `    <div class="accent-tile" data-accent="${esc(a)}">
      <span class="accent-name">${esc(a)}</span>
      ${firstExample}
    </div>`,
    )
    .join("\n");
  // One stage per state: the same examples, mechanically forced into that
  // state via the docs-only mirror rules in the generated lib.css.
  const states = (c.meta.states ?? [])
    .map(
      (s) => `<h3 id="state-${esc(s.state)}"><code>${esc(s.state)}</code></h3>
<p>${esc(s.note)}</p>
<div class="stage">
${c.renderedExamples.map((html) => `  ${withForcedState(html, s.state)}`).join("\n")}
</div>`,
    )
    .join("\n");
  const propsRows = Object.entries(c.contract.props ?? {})
    .map(
      ([name, p]) => `      <tr>
        <th scope="row"><code>${esc(name)}</code></th>
        <td><code>${esc(p.type)}</code></td>
        <td>${p.default !== undefined ? `<code>${esc(p.default)}</code>` : "—"}</td>
        <td>${p.optional ? "yes" : "no"}</td>
        <td>${p.note ? esc(p.note) : ""}</td>
      </tr>`,
    )
    .join("\n");
  const a = c.contract.a11y;
  const a11yItems = (
    [
      ["Semantic structure", a.semanticStructure],
      ["Keyboard", a.keyboard],
      ["Decisions", a.decisions],
      ["Notes", a.notes],
    ] as const
  )
    .filter(([, v]) => v)
    .map(([k, v]) => `    <div><dt>${k}</dt><dd>${esc(v)}</dd></div>`)
    .join("\n");
  return layout({
    title: `${c.meta.name} — LearningLeagues Lib`,
    relRoot: "..",
    accents,
    components,
    tokenSections,
    current: c.slug,
    content: `<h1>${esc(c.meta.name)} <span class="badge badge--${esc(c.contract.status)}">${esc(c.contract.status)}</span></h1>
<p>${esc(c.meta.description)}</p>
<p class="facts">Variants: ${c.meta.variants.map((v) => `<code>${esc(v.variant)}</code>`).join(" ") || "—"} · A11y: <span class="badge badge--${esc(a.status)}">${esc(a.status)}</span></p>
${c.meta.notes ? `<p class="notes">${esc(c.meta.notes)}</p>` : ""}
<p class="meta-links">${c.contract.rfc ? `RFC: <code>${esc(c.contract.rfc)}</code>` : ""}${c.contract.designNode ? ` · Figma node: <code>${esc(c.contract.designNode)}</code>` : ""}</p>
<h2 id="examples">Examples</h2>
<p>Live renders — hover and keyboard states all work here.</p>
${exampleStage}
${guidelinesHtml}<h2 id="accents">The ${accents.length} accents</h2>
<p>Each tile scopes the accent axis with <code>data-accent</code> on the tile itself — the element-scoped theme contract.</p>
<div class="accent-grid">
${accentTiles}
</div>
${
  states
    ? `<h2 id="states">States</h2>
<p>Hover and focus-visible are CSS states, never props (RFC §3). Each stage below shows the examples held in that exact state via docs-only mirror rules derived from the component's own stylesheet.</p>
${states}
`
    : ""
}<h2 id="props">Props</h2>
<table>
  <thead>
    <tr><th scope="col">Prop</th><th scope="col">Type</th><th scope="col">Default</th><th scope="col">Optional</th><th scope="col">Note</th></tr>
  </thead>
  <tbody>
${propsRows}
  </tbody>
</table>
<h2 id="accessibility">Accessibility <span class="badge badge--${esc(a.status)}">${esc(a.status)}</span></h2>
<dl class="a11y">
${a11yItems}
</dl>`,
  });
}

// ── Tokens page ─────────────────────────────────────────────────────────────

const swatch = (e: TokenEntry): string =>
  `<span class="swatch ll-docs-swatch--${esc(e.css.replace(/^--ll-/, ""))}" aria-hidden="true"></span>`;

const spacingBar = (cssVar: string): string =>
  `<span class="bar ll-docs-bar--${esc(cssVar.replace(/^--ll-/, ""))}" aria-hidden="true"></span>`;

function colorTable(
  entries: TokenEntry[],
  valueHeader: string,
  value: (e: TokenEntry) => string,
): string {
  const rows = entries
    .map(
      (e) => `      <tr>
        <td>${swatch(e)}</td>
        <th scope="row"><code>${esc(e.path)}</code></th>
        <td><code>${esc(e.css)}</code></td>
        <td>${value(e)}</td>
      </tr>`,
    )
    .join("\n");
  return `<table>
  <thead>
    <tr><th scope="col">Preview</th><th scope="col">Token</th><th scope="col">CSS property</th><th scope="col">${esc(valueHeader)}</th></tr>
  </thead>
  <tbody>
${rows}
  </tbody>
</table>`;
}

export function tokensPage(
  model: TokenModel,
  components: ComponentDoc[],
  tokenSections: { label: string; anchor: string }[],
): string {
  const byKey = new Map<string, TokenEntry>();
  for (const c of model.collections) for (const e of c.entries) byKey.set(e.key, e);
  const byCollection = (name: string): TokenEntry[] =>
    model.collections.find((c) => c.collection === name)?.entries ?? [];
  const tokenCount = model.collections.reduce((n, c) => n + c.entries.length, 0);

  const sectionBodies: Record<string, string> = {};

  // Primitives: raw values, one table per group.
  const primitives = byCollection("Primitives");
  const groups = [...new Set(primitives.map((e) => e.group))];
  sectionBodies.Primitives =
    `<p>Raw values as extracted from Figma. Components never reference a primitive directly — they consume the semantic aliases below.</p>\n` +
    groups
      .map(
        (g) =>
          `<h3 id="primitives-${esc(g)}"><code>${esc(g)}</code></h3>\n` +
          colorTable(
            primitives.filter((e) => e.group === g),
            "Value",
            (e) => `<code>${esc(e.emitted)}</code>`,
          ),
      )
      .join("\n");

  // Semantic: aliases only — the column shows what each token points at.
  sectionBodies.Semantic =
    `<p>The layer components consume. Every semantic token is an alias of a primitive — none holds a raw value. The previews are live: <code>--ll-accent</code> and its dependents follow the accent switcher above.</p>\n` +
    colorTable(byCollection("Semantic"), "Alias of", (e) => {
      const target = e.aliasOf ? byKey.get(e.aliasOf) : undefined;
      return target ? `<code>${esc(target.css)}</code>` : "—";
    });

  // Spacing: the ladder, sorted by value, each step drawn at its real size.
  const spacing = [...byCollection("Spacing")].sort(
    (a, b) => parseFloat(a.emitted) - parseFloat(b.emitted),
  );
  sectionBodies.Spacing =
    `<p>The spacing ladder, built on the base unit <code>--ll-s</code> (the ladder arithmetic multiplies it: <code>s-275</code> = 2.75 × 8). Each bar is drawn at the token's actual size via its own custom property.</p>\n` +
    `<table>
  <thead>
    <tr><th scope="col">Preview</th><th scope="col">Token</th><th scope="col">CSS property</th><th scope="col">Value</th></tr>
  </thead>
  <tbody>
${spacing
  .map(
    (e) => `      <tr>
        <td class="bar-cell">${spacingBar(e.css)}</td>
        <th scope="row"><code>${esc(e.path)}</code></th>
        <td><code>${esc(e.css)}</code></td>
        <td><code>${esc(e.emitted)}</code></td>
      </tr>`,
  )
  .join("\n")}
  </tbody>
</table>`;

  // Layout: plain values (z/* is unitless by name).
  sectionBodies.Layout =
    `<p>Structural constants: chrome dimensions and the z-index scale.</p>\n` +
    `<table>
  <thead>
    <tr><th scope="col">Token</th><th scope="col">CSS property</th><th scope="col">Value</th></tr>
  </thead>
  <tbody>
${byCollection("Layout")
  .map(
    (e) => `      <tr>
        <th scope="row"><code>${esc(e.path)}</code></th>
        <td><code>${esc(e.css)}</code></td>
        <td><code>${esc(e.emitted)}</code></td>
      </tr>`,
  )
  .join("\n")}
  </tbody>
</table>`;

  // Typography: a specimen per family, with the emitted stack.
  sectionBodies.Typography =
    `<p>Figma stores the bare family; the transform stage adds the web fallback stack shown here.</p>\n` +
    `<table>
  <thead>
    <tr><th scope="col">Specimen</th><th scope="col">Token</th><th scope="col">CSS property</th><th scope="col">Family stack</th></tr>
  </thead>
  <tbody>
${byCollection("Typography")
  .map(
    (e) => `      <tr>
        <td><span class="specimen ll-docs-font--${esc(e.css.replace(/^--ll-/, ""))}">Learning leagues climb the ladder — 0123456789</span></td>
        <th scope="row"><code>${esc(e.path)}</code></th>
        <td><code>${esc(e.css)}</code></td>
        <td><code>${esc(e.emitted)}</code></td>
      </tr>`,
  )
  .join("\n")}
  </tbody>
</table>`;

  // Type: the ramp derived from the type/* text styles — one row per style,
  // specimen rendered by its generated .ll-docs-type--<slug> class.
  const typeEntries = byCollection("Type");
  const typeProp = (slug: string, prop: string) =>
    typeEntries.find((e) => e.group === slug && e.path === `${slug}/${prop}`);
  // Ramp order: size descending (the file's own order is style-creation order).
  const typeSlugs = [...new Set(typeEntries.map((e) => e.group))].sort(
    (a, b) =>
      parseFloat(typeProp(b, "size")?.emitted ?? "0") -
      parseFloat(typeProp(a, "size")?.emitted ?? "0"),
  );
  sectionBodies.Type =
    `<p>Tokens derived from the Figma <code>type/*</code> text styles by the extraction pipeline. Each style is a set of custom properties named <code>--ll-type-&lt;style&gt;-&lt;prop&gt;</code> (family, size, weight, style, line-height, tracking, case); the family aliases the Typography font tokens above. The specimens are rendered by these variables.</p>\n` +
    `<table>
  <thead>
    <tr><th scope="col">Specimen</th><th scope="col">Style</th><th scope="col">size</th><th scope="col">weight</th><th scope="col">line-height</th><th scope="col">tracking</th><th scope="col">case</th></tr>
  </thead>
  <tbody>
${typeSlugs
  .map((slug) => {
    const cell = (prop: string) => {
      const e = typeProp(slug, prop);
      return e ? `<code>${esc(e.emitted)}</code>` : "—";
    };
    return `      <tr>
        <td><span class="ll-docs-type--${esc(slug)}">Climb the ladder</span></td>
        <th scope="row"><code>type/${esc(slug)}</code></th>
        <td>${cell("size")}</td>
        <td>${cell("weight")}</td>
        <td>${cell("line-height")}</td>
        <td>${cell("tracking")}</td>
        <td>${cell("case")}</td>
      </tr>`;
  })
  .join("\n")}
  </tbody>
</table>`;

  const collectionsHtml = tokenSections
    .filter((s) => s.anchor !== "axes")
    .map((s) => {
      const body = sectionBodies[s.label];
      if (body === undefined)
        throw new Error(`tokensPage: no section renderer for collection "${s.label}"`);
      return `<h2 id="${esc(s.anchor)}">${esc(s.label)}</h2>\n${body}`;
    })
    .join("\n");

  const accentChips = model.accents
    .map(
      (a) =>
        `    <span class="chip"><span class="swatch ll-docs-swatch--accent-${esc(a)}" aria-hidden="true"></span>${esc(a)}</span>`,
    )
    .join("\n");
  const roleRows = model.roles
    .map(
      (r) => `      <tr>
        <th scope="row"><code>${esc(r.role)}</code></th>
        <td><code>${esc(r.accent)}</code></td>
        <td><span class="swatch ll-docs-swatch--accent-${esc(r.accent)}" aria-hidden="true"></span></td>
      </tr>`,
    )
    .join("\n");
  const axesHtml = `<h2 id="axes">Theme axes</h2>
<p>There is no light/dark axis — the palette is a single dark theme by design — and no density axis since 2026-08-30. The one theming axis is element-scoped: the host application sets the attribute on the root element or any subtree element, and the subtree inherits it. The bare root defaults to <code>data-accent="ambre"</code>.</p>
<h3 id="axes-accent">Accent — <code>data-accent</code></h3>
<p>Swaps which accent primitive <code>--ll-accent</code> resolves to. Try the switcher in the header — every live preview on this page follows it.</p>
<div class="chips">
${accentChips}
    <span class="chip"><span class="swatch ll-docs-swatch--accent" aria-hidden="true"></span>current (<code>--ll-accent</code>)</span>
</div>
<h3 id="axes-role">Role — <code>data-role</code></h3>
<p>Maps a product role onto an accent; a role attribute wins over an inherited accent in the cascade.</p>
<table>
  <thead>
    <tr><th scope="col">Role</th><th scope="col">Accent</th><th scope="col">Preview</th></tr>
  </thead>
  <tbody>
${roleRows}
  </tbody>
</table>`;

  return layout({
    title: "Design tokens — LearningLeagues Lib",
    relRoot: ".",
    accents: model.accents,
    components,
    tokenSections,
    current: "tokens",
    content: `<h1>Design tokens</h1>
<p>${tokenCount} tokens in the <code>--ll-*</code> namespace. They flow one way only: Figma variables → extraction pipeline → one generated stylesheet. No agent and no developer ever writes a token by hand; this page is generated from the same artefacts the library ships (<code>tokens.json</code> + <code>tokens.css</code>).</p>
${collectionsHtml}
${axesHtml}`,
  });
}
