// HTML templates for the docs generator. Hand-written SHELL semantics live in
// docs/assets/site.css + site.js; everything data-driven here comes from the
// contracts and tokens.json, never hand-added (blueprint §2.3).
export interface ComponentDoc {
  slug: string; // folder name, kebab-case
  meta: {
    name: string;
    description: string;
    variants: { variant: string }[];
    states?: string[];
    notes?: string;
    examples: { label: string; props: Record<string, unknown>; children?: string }[];
  };
  contract: {
    status: string;
    rfc?: string;
    designNode?: string;
    props?: Record<string, { type: string; default?: string; optional?: boolean; note?: string }>;
    a11y: {
      status: string;
      semanticStructure?: string;
      keyboard?: string;
      decisions?: string;
      notes?: string;
    };
  };
  renderedExamples: string[]; // same order as meta.examples
}

export const esc = (s: unknown): string =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const GENERATED =
  "<!-- GENERATED by `pnpm docs:build` (scripts/generate-docs.ts). Do not edit; edit the component contracts and regenerate. -->";

// Generic per-state blurbs (presentation boilerplate, not contract content —
// the component's own prose stays in its contract and renders elsewhere).
const STATE_BLURB: Record<string, string> = {
  default: "The resting chrome — exactly what the examples render.",
  hover: "Pointer over the control. A CSS state, never a prop — try it on any example.",
  "focus-visible": "Keyboard-only focus ring. Tab to an example to see it — never a prop.",
};

// One place defines a component page's section anchors; the sidebar submenu
// and the page headings both read it, so they cannot drift apart.
function sections(c: ComponentDoc): { label: string; anchor: string }[] {
  return [
    { label: "Examples", anchor: "examples" },
    { label: "Accents", anchor: "accents" },
    ...(c.meta.states ?? []).map((s) => ({ label: s, anchor: `state-${s}` })),
    ...(c.contract.props ? [{ label: "Props", anchor: "props" }] : []),
    { label: "Accessibility", anchor: "accessibility" },
  ];
}

function sidebar(components: ComponentDoc[], relRoot: string, currentSlug?: string): string {
  const items = components
    .map((c) => {
      const href = `${relRoot}/components/${esc(c.slug)}.html`;
      const current = c.slug === currentSlug;
      const sub = sections(c)
        .map((s) => `        <li><a href="${href}#${s.anchor}">${esc(s.label)}</a></li>`)
        .join("\n");
      return `    <li>
      <details${current ? " open" : ""}>
        <summary><a href="${href}"${current ? ' aria-current="page"' : ""}>${esc(c.meta.name)}</a></summary>
        <ul class="sub">
${sub}
        </ul>
      </details>
    </li>`;
    })
    .join("\n");
  return `<nav class="sidebar" aria-label="Components">
  <a class="registry-link" href="${relRoot}/index.html"${currentSlug ? "" : ' aria-current="page"'}>Registry</a>
  <p class="sidebar-label">Components</p>
  <ul class="nav-list">
${items}
  </ul>
</nav>`;
}

export function layout(opts: {
  title: string;
  relRoot: string; // "." for index, ".." for component pages
  accents: string[];
  components: ComponentDoc[];
  currentSlug?: string;
  content: string;
}): string {
  const { title, relRoot, accents, components, currentSlug, content } = opts;
  return `<!doctype html>
${GENERATED}
<html lang="en" data-accent="ambre" data-density="compact">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<link rel="stylesheet" href="${relRoot}/assets/lib.css">
<link rel="stylesheet" href="${relRoot}/assets/site.css">
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header">
  <a class="site-title" href="${relRoot}/index.html">LearningLeagues Lib</a>
  <div class="switchers">
    <fieldset class="switcher" aria-label="Accent">
      <legend>Accent</legend>
${accents
  .map(
    (a) =>
      `      <button type="button" data-set-accent="${esc(a)}" aria-pressed="${a === "ambre"}">${esc(a)}</button>`,
  )
  .join("\n")}
    </fieldset>
    <fieldset class="switcher" aria-label="Density">
      <legend>Density</legend>
      <button type="button" data-set-density="compact" aria-pressed="true">compact</button>
      <button type="button" data-set-density="aere" aria-pressed="false">aere</button>
    </fieldset>
  </div>
</header>
<div class="shell">
${sidebar(components, relRoot, currentSlug)}
<main id="main">
${content}
</main>
</div>
<footer class="site-footer">
  <p>Generated from the component contracts by <code>pnpm docs:build</code>. Content lives in the contracts, never here.</p>
</footer>
<script src="${relRoot}/assets/site.js"></script>
</body>
</html>
`;
}

export function indexPage(components: ComponentDoc[], accents: string[]): string {
  const rows = components
    .map(
      (c) => `      <tr>
        <th scope="row"><a href="./components/${esc(c.slug)}.html">${esc(c.meta.name)}</a></th>
        <td><span class="badge badge--${esc(c.contract.status)}">${esc(c.contract.status)}</span></td>
        <td>${c.meta.variants.map((v) => esc(v.variant)).join(", ") || "—"}</td>
        <td><span class="badge badge--${esc(c.contract.a11y.status)}">${esc(c.contract.a11y.status)}</span></td>
        <td>${esc(c.meta.description)}</td>
      </tr>`,
    )
    .join("\n");
  return layout({
    title: "Component registry — LearningLeagues Lib",
    relRoot: ".",
    accents,
    components,
    content: `<h1>Component registry</h1>
<p>Every row is generated from the component's own contract (<code>meta.ts</code> + <code>contract.json</code>).</p>
<table>
  <thead>
    <tr><th scope="col">Component</th><th scope="col">Status</th><th scope="col">Variants</th><th scope="col">A11y</th><th scope="col">Description</th></tr>
  </thead>
  <tbody>
${rows}
  </tbody>
</table>`,
  });
}

export function componentPage(
  c: ComponentDoc,
  accents: string[],
  components: ComponentDoc[],
): string {
  const examples = c.meta.examples
    .map(
      (e, i) => `  <figure class="demo">
    <figcaption>${esc(e.label)}</figcaption>
    <div class="demo-stage">${c.renderedExamples[i]}</div>
  </figure>`,
    )
    .join("\n");
  const firstExample = c.renderedExamples[0] ?? "";
  const accentTiles = accents
    .map(
      (a) => `    <div class="accent-tile" data-accent="${esc(a)}">
      <span class="accent-name">${esc(a)}</span>
      ${firstExample}
    </div>`,
    )
    .join("\n");
  const states = (c.meta.states ?? [])
    .map(
      (s) => `<h3 id="state-${esc(s)}"><code>${esc(s)}</code></h3>
<p>${esc(STATE_BLURB[s] ?? "A CSS state of the component chrome, never a prop.")}</p>`,
    )
    .join("\n");
  const propsRows = Object.entries(c.contract.props ?? {})
    .map(
      ([name, p]) => `      <tr>
        <th scope="row"><code>${esc(name)}</code></th>
        <td><code>${esc(p.type)}</code></td>
        <td>${p.default !== undefined ? `<code>${esc(p.default)}</code>` : "—"}</td>
        <td>${p.optional ? "yes" : "no"}</td>
        <td>${p.note ? esc(p.note) : ""}</td>
      </tr>`,
    )
    .join("\n");
  const a = c.contract.a11y;
  const a11yItems = (
    [
      ["Semantic structure", a.semanticStructure],
      ["Keyboard", a.keyboard],
      ["Decisions", a.decisions],
      ["Notes", a.notes],
    ] as const
  )
    .filter(([, v]) => v)
    .map(([k, v]) => `    <div><dt>${k}</dt><dd>${esc(v)}</dd></div>`)
    .join("\n");
  return layout({
    title: `${c.meta.name} — LearningLeagues Lib`,
    relRoot: "..",
    accents,
    components,
    currentSlug: c.slug,
    content: `<h1>${esc(c.meta.name)} <span class="badge badge--${esc(c.contract.status)}">${esc(c.contract.status)}</span></h1>
<p>${esc(c.meta.description)}</p>
<p class="facts">Variants: ${c.meta.variants.map((v) => `<code>${esc(v.variant)}</code>`).join(" ") || "—"} · A11y: <span class="badge badge--${esc(a.status)}">${esc(a.status)}</span></p>
${c.meta.notes ? `<p class="notes">${esc(c.meta.notes)}</p>` : ""}
<p class="meta-links">${c.contract.rfc ? `RFC: <code>${esc(c.contract.rfc)}</code>` : ""}${c.contract.designNode ? ` · Figma node: <code>${esc(c.contract.designNode)}</code>` : ""}</p>
<h2 id="examples">Examples</h2>
<div class="demos">
${examples}
</div>
<h2 id="accents">The ${accents.length} accents</h2>
<p>Each tile scopes the accent axis with <code>data-accent</code> on the tile itself — the element-scoped theme contract.</p>
<div class="accent-grid">
${accentTiles}
</div>
${
  states
    ? `<h2 id="states">States</h2>
<p>Hover and focus-visible are CSS states, never props (RFC §3).</p>
${states}
`
    : ""
}<h2 id="props">Props</h2>
<table>
  <thead>
    <tr><th scope="col">Prop</th><th scope="col">Type</th><th scope="col">Default</th><th scope="col">Optional</th><th scope="col">Note</th></tr>
  </thead>
  <tbody>
${propsRows}
  </tbody>
</table>
<h2 id="accessibility">Accessibility <span class="badge badge--${esc(a.status)}">${esc(a.status)}</span></h2>
<dl class="a11y">
${a11yItems}
</dl>`,
  });
}
