// Docs-site generator (blueprint §9): builds docs/ from the component
// contracts. Content lives in meta.ts + contract.json and regenerates —
// never hand-add an entry to the generated pages.
// Emits: docs/index.html, docs/components/<slug>.html, docs/assets/lib.css.
// Usage: node scripts/generate-docs.ts [--check]
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { pathToFileURL } from "node:url";
import { renderExamples, type Example } from "./lib/docs-render.ts";
import { indexPage, componentPage, type ComponentDoc } from "./lib/docs-html.ts";

const COMPONENTS_DIR = "packages/ui/src/components";
const TOKENS_JSON = "packages/ui/src/tokens/tokens.json";
const TOKENS_CSS = "packages/ui/src/tokens/tokens.css";
const OUT = "docs";

const errors: string[] = [];
const fail = (msg: string) => errors.push(msg);

// ── Discovery: every component folder carrying a contract, sorted ───────────
const slugs = readdirSync(COMPONENTS_DIR)
  .filter((n) => statSync(join(COMPONENTS_DIR, n)).isDirectory())
  .filter((n) => existsSync(join(COMPONENTS_DIR, n, "contract.json")))
  .sort();

// ── Accent axis names from tokens.json (never hand-listed) ──────────────────
const tokens: Record<string, { css: string }> = JSON.parse(
  readFileSync(TOKENS_JSON, "utf8"),
).tokens;
const accents = Object.keys(tokens)
  .filter((k) => k.startsWith("Primitives/accent/"))
  .map((k) => k.split("/").pop() as string);

const components: ComponentDoc[] = [];
for (const slug of slugs) {
  const dir = join(COMPONENTS_DIR, slug);
  const metaFile = readdirSync(dir).find((n) => n.endsWith(".meta.ts"));
  if (!metaFile) {
    fail(`${slug}: no *.meta.ts contract`);
    continue;
  }
  const { meta } = await import(pathToFileURL(resolve(dir, metaFile)).href);
  const contract = JSON.parse(readFileSync(join(dir, "contract.json"), "utf8"));
  // Loud completeness validation — the precursor of the blueprint §9.1 gate.
  // A page rendering blank with every gate green is a documented failure mode.
  if (typeof meta?.name !== "string" || !meta.name) fail(`${slug}: meta.name missing`);
  if (typeof meta?.description !== "string" || meta.description.startsWith("TODO"))
    fail(`${slug}: meta.description missing or TODO`);
  if (!Array.isArray(meta?.variants)) fail(`${slug}: meta.variants missing`);
  if (!Array.isArray(meta?.examples) || meta.examples.length === 0)
    fail(`${slug}: meta.examples must hold at least one example (blueprint §9.1)`);
  if (meta?.states !== undefined) {
    if (!Array.isArray(meta.states)) fail(`${slug}: meta.states must be an array`);
    else
      for (const s of meta.states)
        if (typeof s?.state !== "string" || !s.state || typeof s?.note !== "string" || !s.note)
          fail(`${slug}: every meta.states entry needs a state name and a note (vs default)`);
  }
  if (typeof contract?.status !== "string") fail(`${slug}: contract.status missing`);
  if (typeof contract?.a11y?.status !== "string") fail(`${slug}: contract.a11y.status missing`);
  if (errors.length) continue;
  const renderedExamples = renderExamples(dir, meta.name, meta.examples as Example[]);
  components.push({ slug, meta, contract, renderedExamples });
}
if (errors.length) {
  console.error("generate-docs: FAILED\n" + errors.map((e) => `  - ${e}`).join("\n"));
  process.exit(1);
}

// ── Outputs (all built in memory first — determinism, then --check or write) ─
const CSS_BANNER = `/* GENERATED by \`pnpm docs:build\` (scripts/generate-docs.ts): tokens.css +
 * every component stylesheet, concatenated so docs/ is self-contained.
 * Do not edit; the sources are the library stylesheets. */\n\n`;
const componentCss = components
  .flatMap((c) =>
    readdirSync(join(COMPONENTS_DIR, c.slug))
      .filter((n) => n.endsWith(".css"))
      .sort()
      .map((n) => readFileSync(join(COMPONENTS_DIR, c.slug, n), "utf8")),
  )
  .join("\n");
// Docs-only forced-state mirrors: every component rule keyed on a state
// pseudo-class is duplicated with a `.ll-docs-force-<state>` class selector, so
// a static page can hold a component in that exact state. Mechanically derived
// from the component css — the single source — never hand-written.
const PSEUDO_STATES = ["hover", "focus-visible", "active"];
function forceStateRules(css: string): string {
  const mirrored: string[] = [];
  for (const m of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
    const sel = m[1].replace(/\/\*[\s\S]*?\*\//g, "").trim();
    if (!PSEUDO_STATES.some((s) => sel.includes(`:${s}`))) continue;
    const forced = sel
      .split(",")
      .map((one) =>
        PSEUDO_STATES.reduce(
          (acc, s) => acc.split(`:${s}`).join(`.ll-docs-force-${s}`),
          one.trim(),
        ),
      )
      .join(",\n");
    mirrored.push(`${forced} {${m[2]}}`);
  }
  if (mirrored.length === 0) return "";
  return (
    "\n/* Docs-only forced-state mirrors — derived by `pnpm docs:build` from the\n" +
    " * component rules above; never hand-written. */\n" +
    mirrored.join("\n") +
    "\n"
  );
}

const outputs: Record<string, string> = {
  [join(OUT, "assets", "lib.css")]:
    CSS_BANNER +
    readFileSync(TOKENS_CSS, "utf8") +
    "\n" +
    componentCss +
    forceStateRules(componentCss),
  [join(OUT, "index.html")]: indexPage(components, accents),
};
for (const c of components)
  outputs[join(OUT, "components", `${c.slug}.html`)] = componentPage(c, accents, components);

if (process.argv.includes("--check")) {
  const stale = Object.entries(outputs).filter(
    ([path, content]) => !existsSync(path) || readFileSync(path, "utf8") !== content,
  );
  if (stale.length) {
    console.error(
      `generate-docs --check: DRIFT — stale docs. Run: pnpm docs:build\n` +
        stale.map(([p]) => `  - ${p}`).join("\n"),
    );
    process.exit(1);
  }
  console.log("generate-docs --check: OK");
} else {
  for (const [path, content] of Object.entries(outputs)) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`generate-docs: wrote ${path}`);
  }
}
