// Consumer dist generator (distribution contract, phase 1 adapted to a
// buildless host): builds dist/ from the same sources the docs site renders.
// - dist/ll-lib.css   — tokens.css + every component stylesheet, concatenated
//   (no docs-only rules; the library still ships no global reset).
// - dist/ll-lib.jsx   — every component's real .tsx, types stripped and JSX
//   PRESERVED (esbuild), exported as window.LL globals for a host that loads
//   React UMD + Babel standalone. Never a hand-port (axiom 4).
// The host vendors these files at a pinned commit via scripts/vendor-dist.ts.
// Usage: node scripts/generate-dist.ts [--check]
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { pathToFileURL } from "node:url";
import { transformSync } from "esbuild";

const COMPONENTS_DIR = "packages/ui/src/components";
const TOKENS_CSS = "packages/ui/src/tokens/tokens.css";
const OUT = "dist";

const errors: string[] = [];

const slugs = readdirSync(COMPONENTS_DIR)
  .filter((n) => statSync(join(COMPONENTS_DIR, n)).isDirectory())
  .filter((n) => existsSync(join(COMPONENTS_DIR, n, "contract.json")))
  .sort();

const CSS_BANNER = `/* GENERATED by \`pnpm dist:build\` (scripts/generate-dist.ts): tokens.css +
 * every component stylesheet, concatenated for a consuming host. Do not edit;
 * the sources are the library stylesheets. No global reset ships here
 * (distribution contract): the host owns its reset. */\n\n`;

const JSX_BANNER = `/* GENERATED by \`pnpm dist:build\` (scripts/generate-dist.ts): the real
 * component sources, types stripped, JSX preserved (esbuild), exposed as
 * window.LL globals for a buildless host (React UMD + Babel standalone).
 * Do not edit; edit the component .tsx sources and regenerate. */\n\n`;

const cssParts: string[] = [];
const jsxParts: string[] = [];
const exportNames: string[] = [];

for (const slug of slugs) {
  const dir = join(COMPONENTS_DIR, slug);
  const metaFile = readdirSync(dir).find((n) => n.endsWith(".meta.ts"));
  if (!metaFile) {
    errors.push(`${slug}: no *.meta.ts contract`);
    continue;
  }
  const { meta } = await import(pathToFileURL(resolve(dir, metaFile)).href);
  if (typeof meta?.name !== "string" || !meta.name) {
    errors.push(`${slug}: meta.name missing`);
    continue;
  }
  for (const n of readdirSync(dir)
    .filter((f) => f.endsWith(".css"))
    .sort())
    cssParts.push(readFileSync(join(dir, n), "utf8"));
  const tsxFile = readdirSync(dir).find((n) => n === `${meta.name}.tsx`);
  if (!tsxFile) {
    errors.push(`${slug}: no ${meta.name}.tsx source`);
    continue;
  }
  const source = readFileSync(join(dir, tsxFile), "utf8");
  const out = transformSync(source, { loader: "tsx", jsx: "preserve" }).code;
  // The host provides React as a global (UMD) and loads this file as a
  // classic script: drop the module import, unwrap the export keyword.
  const stripped = out
    .replace(/^import React from "react";\n/m, "")
    .replace(/^export (function|const) /gm, "$1 ");
  if (/^(import|export) /m.test(stripped)) {
    errors.push(`${slug}: residual import/export after stripping — teach generate-dist the shape`);
    continue;
  }
  jsxParts.push(`// ── ${meta.name} (${slug}) ──\n${stripped.trimEnd()}\n`);
  exportNames.push(meta.name);
}
if (errors.length === 0 && exportNames.length === 0) errors.push("no components discovered");
if (errors.length) {
  console.error("generate-dist: FAILED\n" + errors.map((e) => `  - ${e}`).join("\n"));
  process.exit(1);
}

const outputs: Record<string, string> = {
  [join(OUT, "ll-lib.css")]:
    CSS_BANNER + readFileSync(TOKENS_CSS, "utf8") + "\n" + cssParts.join("\n"),
  [join(OUT, "ll-lib.jsx")]:
    JSX_BANNER +
    jsxParts.join("\n") +
    `\nwindow.LL = Object.assign(window.LL || {}, { ${exportNames.join(", ")} });\n`,
};

if (process.argv.includes("--check")) {
  const stale = Object.entries(outputs).filter(
    ([path, content]) => !existsSync(path) || readFileSync(path, "utf8") !== content,
  );
  if (stale.length) {
    console.error(
      `generate-dist --check: DRIFT — stale dist. Run: pnpm dist:build\n` +
        stale.map(([p]) => `  - ${p}`).join("\n"),
    );
    process.exit(1);
  }
  console.log("generate-dist --check: OK");
} else {
  for (const [path, content] of Object.entries(outputs)) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`generate-dist: wrote ${path}`);
  }
}
