// Stage 2 — normalize: raw Figma export -> tokens.json (interchange format).
// Usage: node scripts/extract-tokens/normalize.ts [--check]
// --check regenerates in memory and fails on drift with the committed file.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const RAW = "packages/ui/src/tokens/raw/figma-variables.json";
const OUT = "packages/ui/src/tokens/tokens.json";

interface RawVariable {
  id: string;
  name: string;
  variableCollectionId: string;
  resolvedType: "COLOR" | "FLOAT" | "STRING" | "BOOLEAN";
  scopes: string[];
  codeSyntax: { WEB?: string };
  valuesByMode: Record<string, unknown>;
}
interface RawExport {
  collections: { id: string; name: string }[];
  variables: RawVariable[];
}

const raw: RawExport = JSON.parse(readFileSync(RAW, "utf8"));
const collectionName = new Map(raw.collections.map((c) => [c.id, c.name]));
const byId = new Map(raw.variables.map((v) => [v.id, v]));

const errors: string[] = [];
const cssOf = (v: RawVariable): string => {
  const web = v.codeSyntax?.WEB ?? "";
  const m = web.match(/^var\((--ll-[a-z0-9-]+)\)$/);
  if (!m) {
    errors.push(`${v.name}: WEB code syntax ${JSON.stringify(web)} does not match var(--ll-*)`);
    return "";
  }
  return m[1];
};
const toColor = (c: { r: number; g: number; b: number; a: number }): string => {
  const ch = (x: number) => Math.round(x * 255);
  const hex = "#" + [c.r, c.g, c.b].map((x) => ch(x).toString(16).padStart(2, "0")).join("");
  if (Math.abs(c.a - 1) < 1e-6) return hex;
  return `rgba(${ch(c.r)}, ${ch(c.g)}, ${ch(c.b)}, ${Math.round(c.a * 100) / 100})`;
};

type TokenValue = string | number | { alias: string };
const tokens: Record<string, { type: string; css: string; scopes: string[]; value: TokenValue }> =
  {};

const keyOf = (v: RawVariable) => `${collectionName.get(v.variableCollectionId)}/${v.name}`;

for (const v of raw.variables) {
  const modeValues = Object.values(v.valuesByMode);
  if (modeValues.length !== 1) {
    errors.push(`${v.name}: expected exactly 1 mode value, got ${modeValues.length}`);
    continue;
  }
  const rawValue = modeValues[0] as Record<string, unknown>;
  let value: TokenValue;
  if (rawValue && typeof rawValue === "object" && rawValue.type === "VARIABLE_ALIAS") {
    const target = byId.get(rawValue.id as string);
    if (!target) {
      errors.push(`${v.name}: dangling alias ${rawValue.id}`);
      continue;
    }
    value = { alias: keyOf(target) };
  } else if (v.resolvedType === "COLOR") {
    value = toColor(rawValue as unknown as { r: number; g: number; b: number; a: number });
  } else {
    value = rawValue as unknown as string | number;
  }
  tokens[keyOf(v)] = { type: v.resolvedType.toLowerCase(), css: cssOf(v), scopes: v.scopes, value };
}

if (errors.length) {
  console.error("normalize: FAILED\n" + errors.map((e) => `  - ${e}`).join("\n"));
  process.exit(1);
}

const output =
  JSON.stringify(
    {
      $comment: "GENERATED by `pnpm tokens:normalize` from raw/figma-variables.json — do not edit.",
      tokens,
    },
    null,
    2,
  ) + "\n";

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== output) {
    console.error(
      `normalize --check: DRIFT — ${OUT} does not match its source. Run: pnpm tokens:build`,
    );
    process.exit(1);
  }
  console.log("normalize --check: OK");
} else {
  writeFileSync(OUT, output);
  console.log(`normalize: wrote ${OUT} (${Object.keys(tokens).length} tokens)`);
}
