// Stage 3 — transform: tokens.json -> the library's single generated stylesheet.
// Usage: node scripts/extract-tokens/transform.ts [--check]
// This is the only pipeline stage containing judgement; every judgement is a
// documented override below, keyed on token identity.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const IN = "packages/ui/src/tokens/tokens.json";
const OUT = "packages/ui/src/tokens/tokens.css";

interface Token {
  type: string;
  css: string;
  scopes: string[];
  value: string | number | { alias: string };
}
const data: { tokens: Record<string, Token> } = JSON.parse(readFileSync(IN, "utf8"));
const tokens = data.tokens;
const errors: string[] = [];

// ── Documented overrides ────────────────────────────────────────────────────
// Font stacks: Figma stores a bare family name; the web needs fallbacks.
// Keyed on token identity (blueprint §3.5.1 — correct in the transform, never
// post-export). Changing a family in Figma without updating this map fails loudly.
const FONT_STACKS: Record<string, Record<string, string>> = {
  "Typography/font/display": { "EB Garamond": "'EB Garamond', 'Iowan Old Style', Georgia, serif" },
  "Typography/font/body": { Inter: "'Inter', ui-sans-serif, system-ui, sans-serif" },
  "Typography/font/mono": { "JetBrains Mono": "'JetBrains Mono', ui-monospace, Menlo, monospace" },
};
// Role -> accent mapping (design decision, mirrors the site's historical
// [data-role] cascade; support intentionally equals ambre).
const ROLE_ACCENT: Record<string, string> = {
  support: "ambre",
  adc: "bleu",
  top: "rouge",
  mid: "violet",
  jungle: "jade",
};
// Unit rule per collection for FLOAT tokens; z/* is unitless by name.
const px = (n: number) => `${n}px`;

const cssName = (key: string): string => {
  const t = tokens[key];
  if (!t) errors.push(`transform: unknown token ${key}`);
  return t ? t.css : "";
};
const resolveValue = (key: string, t: Token): string => {
  const v = t.value;
  if (typeof v === "object" && v !== null && "alias" in v) return `var(${cssName(v.alias)})`;
  if (t.type === "color") return String(v);
  if (t.type === "string") {
    const stack = FONT_STACKS[key];
    if (stack) {
      if (!stack[String(v)]) {
        errors.push(
          `${key}: family ${JSON.stringify(v)} has no stack override — add it to FONT_STACKS`,
        );
        return String(v);
      }
      return stack[String(v)];
    }
    return String(v);
  }
  // number
  if (key.startsWith("Layout/z/")) return String(v);
  return px(Number(v));
};

const entries = Object.entries(tokens);
const inCollection = (c: string) => entries.filter(([k]) => k.startsWith(`${c}/`));
const densityPair = inCollection("Spacing").filter(([k]) => k.includes("/density/"));
const accents = inCollection("Primitives")
  .filter(([k]) => k.startsWith("Primitives/accent/"))
  .map(([k]) => k.split("/").pop() as string);

const lines: string[] = [];
lines.push("/* GENERATED by `pnpm tokens:build` from packages/ui/src/tokens/tokens.json.");
lines.push(" * Do not edit token declarations by hand. The ONLY agent-extensible zone is");
lines.push(" * the utilities block at the end of this file.");
lines.push(" * Source of truth: Figma file `Lib` (see tokens/PROVENANCE.md). */");
lines.push("");
lines.push(":root {");
for (const [key, t] of entries) {
  if (key.includes("/density/")) continue; // emitted via the density axis below
  lines.push(`  ${t.css}: ${resolveValue(key, t)};`);
}
// Default density: compact (mirrors the site's historical default).
const compact = tokens["Spacing/density/base-compact"];
if (!compact) errors.push("transform: Spacing/density/base-compact missing");
else lines.push(`  --ll-s: ${px(Number(compact.value))};`);
lines.push("}");
lines.push("");
lines.push("/* Accent axis — the host sets [data-accent] on the root element or any subtree. */");
for (const a of accents) {
  lines.push(`[data-accent="${a}"] {`);
  lines.push(`  --ll-accent: var(--ll-accent-${a});`);
  lines.push("}");
}
lines.push("");
lines.push("/* Role axis — placed AFTER [data-accent] so a role accent wins the cascade. */");
for (const [role, accent] of Object.entries(ROLE_ACCENT)) {
  if (!accents.includes(accent))
    errors.push(`ROLE_ACCENT: role ${role} points at unknown accent ${accent}`);
  lines.push(`[data-role="${role}"] {`);
  lines.push(`  --ll-accent: var(--ll-accent-${accent});`);
  lines.push("}");
}
lines.push("");
lines.push("/* Density axis — the host sets [data-density] on the root element or any subtree. */");
for (const [key, t] of densityPair) {
  const name = key.split("/").pop()!.replace("base-", "");
  lines.push(`[data-density="${name}"] {`);
  lines.push(`  ${t.css}: ${px(Number(t.value))};`);
  lines.push("}");
}
lines.push("");
lines.push("/* utilities (agent-extensible zone) — none yet */");

if (errors.length) {
  console.error("transform: FAILED\n" + errors.map((e) => `  - ${e}`).join("\n"));
  process.exit(1);
}
const output = lines.join("\n") + "\n";

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== output) {
    console.error(
      `transform --check: DRIFT — ${OUT} does not match its source. Run: pnpm tokens:build`,
    );
    process.exit(1);
  }
  console.log("transform --check: OK");
} else {
  writeFileSync(OUT, output);
  console.log(`transform: wrote ${OUT}`);
}
